### PR TITLE
Remove FF for required region

### PR DESCRIPTION
**Pull request by MarekMichali**
**Description**

Removal of the feature flags that were added in [this](https://github.com/kyma-project/control-plane/issues/3006) story.

Changes proposed in this pull request:

- Remove feature flag for exposing schema with required region.
- Remove feature flag for making the region mandatory.

**Related issue(s)**

### CODE REVIEW

**Comment by MarekMichali** [comment]
test pre-kyma-environment-broker

**Review by jaroslaw-pieszka — APPROVED** [review]

**Pull request merged**
