### PR TITLE
Removal of Subscription Cleanup Job from KEB

### PR DESCRIPTION
**Pull request by ralikio**
**Description**

Changes proposed in this pull request:

- Removal of Subscription Cleanup Job Leftovers from KEB.

**Related issue(s)**

https://github.com/kyma-project/control-plane/issues/3249

### CODE REVIEW

**Review by jaroslaw-pieszka — DISMISSED** [review]

**Review by jaroslaw-pieszka — APPROVED** [review]

**Comment by Disper** [comment]
@ralikio should this PR be closed?

**Comment by ralikio** [comment]
> @ralikio should this PR be closed?

@Disper this PR can be merged now.

**Review by VOID404 — APPROVED** [review]

**Pull request merged**
